### ISSUE TITLE
Show DatePicker Calendar Inline instead of as a popup DIV

### ISSUE THREAD

**Issue by jasondavis** [aef-/jquery.filthypillow#26]
I am currently searching for just the right Date Selector/Picker library for a Project Management application.  I will have Project Tasks shown in a popup Modal window when clicked on and in this module I will need to populate the contents of the modal with the Task record details whenever a Task is clicked on in a list of Tasks.

In my Task Modal will be a few Date input fields that will show up as text like this `MM/DD/YYYY` and when a user clicks on a date, it will need to reveal an inline Date Picker calendar with the date value selected from that Task record.  A user can then select any date just as a typical popup date picker works except it will be shown inline instead of as a popup.

After user selects a new date value, it will send an AJAX POST to save the new Date value for that particular task.

This library called `X-Editable` has support for making a Date Picker edit-inplace and save to a backend script however it only works with jQueryUI and Bootstrap DatePickers.

For that reason I am trying to find and implement the functionality I described above into other more lightweight Date Picker libraries.

FilthyPillow looks like it could be a nice starting point since it has some events set up too work in my in-line editing/saving to the backend!  However I notice when clicking to launch the DatePicker it then inserts the calendar into the DOM and then removes it after selection.

This would be just fine however I would need to make it show inline when my Date text is clicked on instead of opening as a popup like it does now.

Does anyone know if it would be fairly easy to make this open inline, perhaps even make it into an option like some other DatePickers do?

**Comment by aef-** [comment]
Hi Jason, so when you say you want to open the calender inline, that means you want to be able to edit the text in the input and have it be reflected in the calendar?

FP supports that _in a way_. It supports key presses, you can use arrows and numbers to select the date/time and it does so smartly so it moves on to the next one (01 month, automatically highlights day), I like it since it prevents the user from messing things up regardless of date format. If that doesn't suffice it shouldn't be take too much work to disable that and edit the input directly.
